// YTypingのローマ字変換マップ（移植版）

export const ALPHABET_LIST = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"]
export const NUM_LIST = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]

// prettier-ignore
export const ROMA_MAP = new Map([
  ["ぎゃ", ["gya", "gilya", "gixya"]],
  ["ぎぃ", ["gyi", "gili", "gixi", "gilyi", "gixyi"]],
  ["ぎゅ", ["gyu", "gilyu", "gixyu"]],
  ["ぎぇ", ["gye", "gile", "gixe", "gilye", "gixye"]],
  ["ぎょ", ["gyo", "gilyo", "gixyo"]],
  ["きゃ", ["kya", "kilya", "kixya"]],
  ["きぃ", ["kyi", "kili", "kixi", "kilyi", "kixyi"]],
  ["きゅ", ["kyu", "kilyu", "kixyu"]],
  ["きぇ", ["kye", "kile", "kixe", "kilye", "kixye"]],
  ["きょ", ["kyo", "kilyo", "kixyo"]],
  ["ぐぁ", ["gwa", "gula", "guxa"]],
  ["ぐぃ", ["gwi", "guli", "guxi", "gulyi", "guxyi"]],
  ["ぐぅ", ["gwu", "gulu", "guxu"]],
  ["ぐぇ", ["gwe", "gule", "guxe", "gulye", "guxye"]],
  ["ぐぉ", ["gwo", "gulo", "guxo"]],
  ["しゃ", ["sya", "sha", "silya", "sixya", "shilya", "shixya", "cilya", "cixya"]],
  ["しぃ", ["syi", "sili", "sixi", "silyi", "shixyi", "shili", "shixi", "shilyi", "shixyi", "cili", "cixi", "cilyi", "cixyi"]],
  ["しゅ", ["syu", "shu", "silyu", "sixyu", "shilyu", "shixyu", "cilyu", "cixyu"]],
  ["しぇ", ["sye", "she", "sile", "sixe", "silye", "sixye", "shile", "shixe", "shilye", "shixye", "cile", "cixe", "cilye", "cixye"]],
  ["しょ", ["syo", "sho", "silyo", "sixyo", "shilyo", "shixyo", "cilyo", "cixyo"]],
  ["じゃ", ["ja", "zya", "jya", "jilya", "jixya", "zilya", "zixya"]],
  ["じぃ", ["zyi", "jyi", "jili", "jixi", "jilyi", "jixyi", "zili", "zixi", "zilyi", "zixyi"]],
  ["じゅ", ["ju", "zyu", "jyu", "jilyu", "jixyu", "zilyu", "zixyu"]],
  ["じぇ", ["je", "zye", "jye", "jile", "jixe", "jilye", "jixye", "zile", "zixe", "zilye", "zixye"]],
  ["じょ", ["jo", "zyo", "jyo", "jilyo", "jixyo", "zilyo", "zixyo"]],
  ["すぁ", ["swa", "sula", "suxa"]],
  ["すぃ", ["swi", "suli", "suxi", "sulyi", "suxyi"]],
  ["すぅ", ["swu", "sulu", "suxu"]],
  ["すぇ", ["swe", "sule", "suxe", "sulye", "suxye"]],
  ["すぉ", ["swo", "sulo", "suxo"]],
  ["ちゃ", ["tya", "cya", "cha", "tilya", "tixya", "chilya", "chixya"]],
  ["ちぃ", ["tyi", "cyi", "tili", "tixi", "tilyi", "tixyi", "chili", "chixi", "chilyi", "chixyi"]],
  ["ちゅ", ["tyu", "cyu", "chu", "tilyu", "tixyu", "chilyu", "chixyu"]],
  ["ちぇ", ["tye", "cye", "che", "tile", "tixe", "tilye", "tixye", "chile", "chixe", "chilye", "chixye"]],
  ["ちょ", ["tyo", "cyo", "cho", "tilyo", "tixyo", "chilyo", "chixyo"]],
  ["ぢゃ", ["dya", "dilya", "dixya"]],
  ["ぢぃ", ["dyi", "dili", "dixi", "dilyi", "dixyi"]],
  ["ぢゅ", ["dyu", "dilyu", "dixyu"]],
  ["ぢぇ", ["dye", "dile", "dixe", "dilye", "dixye"]],
  ["ぢょ", ["dyo", "dilyo", "dixyo"]],
  ["つぁ", ["tsa", "tula", "tuxa", "tsula", "tsuxa"]],
  ["つぃ", ["tsi", "tuli", "tuxi", "tulyi", "tuxyi", "tsuli", "tsuxi", "tsulyi", "tsuxyi"]],
  ["つぇ", ["tse", "tule", "tuxe", "tulye", "tuxye", "tsule", "tsuxe", "tsulye", "tsuxye"]],
  ["つぉ", ["tso", "tulo", "tuxo", "tsulo", "tsuxo"]],
  ["てゃ", ["tha", "telya", "texya"]],
  ["てぃ", ["thi", "t'i", "teli", "texi", "telyi", "texyi"]],
  ["てゅ", ["thu", "t'yu", "telyu", "texyu"]],
  ["てぇ", ["the", "tele", "texe", "telye", "texye"]],
  ["てょ", ["tho", "telyo", "texyo"]],
  ["でゃ", ["dha", "delya", "dexya"]],
  ["でぃ", ["dhi", "d'i", "deli", "dexi", "delyi", "dexyi"]],
  ["でゅ", ["dhu", "d'yu", "delyu", "dexyu"]],
  ["でぇ", ["dhe", "dele", "dexe", "delye", "dexye"]],
  ["でょ", ["dho", "delyo", "dexyo"]],
  ["とぁ", ["twa", "tola", "toxa"]],
  ["とぃ", ["twi", "toli", "toxi", "tolyi", "toxyi"]],
  ["とぅ", ["twu", "t'u", "tolu", "toxu"]],
  ["とぇ", ["twe", "tole", "toxe", "tolye", "toxye"]],
  ["とぉ", ["two", "tolo", "toxo"]],
  ["どぁ", ["dwa", "dola", "doxa"]],
  ["どぃ", ["dwi", "doli", "doxi", "dolyi", "doxyi"]],
  ["どぅ", ["dwu", "d'u", "dolu", "doxu"]],
  ["どぇ", ["dwe", "dole", "doxe", "dolye", "doxye"]],
  ["どぉ", ["dwo", "dolo", "doxo"]],
  ["にゃ", ["nya", "nilya", "nixya"]],
  ["にぃ", ["nyi", "nili", "nixi", "nilyi", "nixyi"]],
  ["にゅ", ["nyu", "nilyu", "nixyu"]],
  ["にぇ", ["nye", "nile", "nixe", "nilye", "nixye"]],
  ["にょ", ["nyo", "nilyo", "nixyo"]],
  ["ひゃ", ["hya", "hilya", "hixya"]],
  ["ひぃ", ["hyi", "hili", "hixi", "hilyi", "hixyi"]],
  ["ひゅ", ["hyu", "hilyu", "hixyu"]],
  ["ひぇ", ["hye", "hile", "hixe", "hilye", "hixye"]],
  ["ひょ", ["hyo", "hilyo", "hixyo"]],
  ["ぴゃ", ["pya", "pilya", "pixya"]],
  ["ぴぃ", ["pyi", "pili", "pixi", "pilyi", "pixyi"]],
  ["ぴゅ", ["pyu", "pilyu", "pixyu"]],
  ["ぴぇ", ["pye", "pile", "pixe", "pilye", "pixye"]],
  ["ぴょ", ["pyo", "pilyo", "pixyo"]],
  ["びゃ", ["bya", "bilya", "bixya"]],
  ["びぃ", ["byi", "bili", "bixi", "bilyi", "bixyi"]],
  ["びゅ", ["byu", "bilyu", "bixyu"]],
  ["びぇ", ["bye", "bile", "bixe", "bilye", "bixye"]],
  ["びょ", ["byo", "bilyo", "bixyo"]],
  ["ヴぁ", ["va", "vula", "vuxa"]],
  ["ヴぃ", ["vi", "vyi", "vuli", "vuxi", "vulyi", "vuxyi"]],
  ["ヴぇ", ["ve", "vye", "vule", "vuxe", "vulye", "vuxye"]],
  ["ヴぉ", ["vo", "vulo", "vuxo"]],
  ["ヴゃ", ["vya", "vulya", "vuxya"]],
  ["ヴゅ", ["vyu", "vulyu", "vuxyu"]],
  ["ヴょ", ["vyo", "vulyo", "vuxyo"]],
  ["ふぁ", ["fa", "fwa", "hwa", "fula", "fuxa", "hula", "huxa"]],
  ["ふぃ", ["fi", "fwi", "hwi", "fuli", "fuxi", "fulyi", "fuxyi", "huli", "huxi", "hulyi", "huxyi"]],
  ["ふぅ", ["fwu", "fulu", "fuxu", "hulu", "huxu"]],
  ["ふぇ", ["fe", "fwe", "fye", "hwe", "fule", "fuxe", "fulye", "fuxye", "hule", "huxe", "hulye", "huxye"]],
  ["ふぉ", ["fo", "fwo", "hwo", "fulo", "fuxo", "hulo", "huxo"]],
  ["ふゃ", ["fya", "fulya", "fuxya", "hulya", "huxya"]],
  ["ふゅ", ["fyu", "hwyu", "fulyu", "fuxyu", "hulyu", "huxyu"]],
  ["ふょ", ["fyo", "fulyo", "fuxyo", "hulyo", "huxyo"]],
  ["みゃ", ["mya", "milya", "mixya"]],
  ["みぃ", ["myi", "mili", "mixi", "milyi", "mixyi"]],
  ["みゅ", ["myu", "milyu", "mixyu"]],
  ["みぇ", ["mye", "mile", "mixe", "milye", "mixye"]],
  ["みょ", ["myo", "milyo", "mixyo"]],
  ["りゃ", ["rya", "rilya", "rixya"]],
  ["りぃ", ["ryi", "rili", "rixi", "rilyi", "rixyi"]],
  ["りゅ", ["ryu", "rilyu", "rixyu"]],
  ["りぇ", ["rye", "rile", "rixe", "rilye", "rixye"]],
  ["りょ", ["ryo", "rilyo", "rixyo"]],
  ["いぇ", ["ye", "ile", "ixe", "ilye", "ixye", "yile", "yixe", "yilye", "yixye"]],
  ["うぁ", ["wha", "ula", "uxa", "wula", "wuxa", "whula", "whuxa"]],
  ["うぃ",["wi", "whi", "uli", "uxi", "ulyi", "uxyi", "wuli", "wuxi", "wulyi", "wuxyi", "whuli", "whuxi", "whulyi", "whuxyi"]],
  ["うぇ",["we", "whe", "ule", "uxe", "ulye", "uxye", "wule", "wuxe", "wulye", "wuxye", "whule", "whuxe", "whulye", "whuxye"]],
  ["うぉ", ["who", "ulo", "uxo", "wulo", "wuxo", "whulo", "whuxo"]],
  ["くぁ", ["qa", "qwa", "kwa", "kula", "kuxa", "qula", "quxa", "cula", "cuxa"]],
  ["くぃ", ["qi", "qwi", "qyi", "kwi", "kuli", "kuxi", "kulyi", "kuxyi", "quli", "quxi", "qulyi", "quxyi", "culi", "cuxi", "culyi", "cuxyi"]],
  ["くぅ", ["qwu", "kwu", "kulu", "kuxu", "qulu", "quxu", "culu", "cuxu"]],
  ["くぇ", ["qe", "qwe", "qye", "kwe", "kule", "kuxe", "kulye", "kuxye", "qule", "quxe", "qulye", "quxye", "cule", "cuxe", "culye", "cuxye"]],
  ["くぉ", ["qo", "qwo", "kwo", "kulo", "kuxo", "qulo", "quxo", "culo", "cuxo"]],
  ["くゃ", ["qya", "kulya", "kuxya", "qulya", "quxya", "culya", "cuxya"]],
  ["くゅ", ["qyu", "kulyu", "kuxyu", "qulyu", "quxyu", "culyu", "cuxyu"]],
  ["くょ", ["qyo", "kulyo", "kuxyo", "qulyo", "quxyo", "culyo", "cuxyo"]],
  ["あ", ["a"]],
  ["い", ["i", "yi"]],
  ["う", ["u", "wu", "whu"]],
  ["え", ["e"]],
  ["お", ["o"]],
  ["か", ["ka", "ca"]],
  ["き", ["ki"]],
  ["く", ["ku", "cu", "qu"]],
  ["け", ["ke"]],
  ["こ", ["ko", "co"]],
  ["さ", ["sa"]],
  ["し", ["si", "ci", "shi"]],
  ["す", ["su"]],
  ["せ", ["se", "ce"]],
  ["そ", ["so"]],
  ["た", ["ta"]],
  ["ち", ["ti", "chi"]],
  ["つ", ["tu", "tsu"]],
  ["て", ["te"]],
  ["と", ["to"]],
  ["な", ["na"]],
  ["に", ["ni"]],
  ["ぬ", ["nu"]],
  ["ね", ["ne"]],
  ["の", ["no"]],
  ["は", ["ha"]],
  ["ひ", ["hi"]],
  ["ふ", ["hu", "fu"]],
  ["へ", ["he"]],
  ["ほ", ["ho"]],
  ["ま", ["ma"]],
  ["み", ["mi"]],
  ["む", ["mu"]],
  ["め", ["me"]],
  ["も", ["mo"]],
  ["や", ["ya"]],
  ["ゆ", ["yu"]],
  ["よ", ["yo"]],
  ["ら", ["ra"]],
  ["り", ["ri"]],
  ["る", ["ru"]],
  ["れ", ["re"]],
  ["ろ", ["ro"]],
  ["わ", ["wa"]],
  ["を", ["wo"]],
  ["ん", ["n", "xn"]],
  ["ヴ", ["vu"]],
  ["が", ["ga"]],
  ["ぎ", ["gi"]],
  ["ぐ", ["gu"]],
  ["げ", ["ge"]],
  ["ご", ["go"]],
  ["ざ", ["za"]],
  ["じ", ["zi", "ji"]],
  ["ず", ["zu"]],
  ["ぜ", ["ze"]],
  ["ぞ", ["zo"]],
  ["だ", ["da"]],
  ["ぢ", ["di"]],
  ["づ", ["du"]],
  ["で", ["de"]],
  ["ど", ["do"]],
  ["ば", ["ba"]],
  ["び", ["bi"]],
  ["ぶ", ["bu"]],
  ["べ", ["be"]],
  ["ぼ", ["bo"]],
  ["ぱ", ["pa"]],
  ["ぴ", ["pi"]],
  ["ぷ", ["pu"]],
  ["ぺ", ["pe"]],
  ["ぽ", ["po"]],
  ["ぁ", ["xa", "la"]],
  ["ぃ", ["xi", "li", "lyi", "xyi"]],
  ["ぅ", ["xu", "lu"]],
  ["ぇ", ["xe", "le", "lye", "xye"]],
  ["ぉ", ["xo", "lo"]],
  ["ゃ", ["xya", "lya"]],
  ["ゅ", ["xyu", "lyu"]],
  ["ょ", ["xyo", "lyo"]],
  ["ゎ", ["xwa", "lwa"]],
  ["っ", ["xtu", "ltu", "xtsu", "ltsu"]],
  ["ヵ", ["xka", "lka"]],
  ["ヶ", ["xke", "lke"]],
  ["ヰ", ["wyi"]],
  ["ゐ", ["wyi"]],
  ["ヱ", ["wye"]],
  ["ゑ", ["wye"]],
])

export const SYMBOL_TO_ROMA_MAP = new Map([
  ["、", [","]],
  ["。", ["."]],
  ["ー", ["-"]],
  ["←", ["zh"]],
  ["↓", ["zj"]],
  ["↑", ["zk"]],
  ["→", ["zl"]],
  ["『", ["z["]],
  ["』", ["z]"]],
  ["～", ["~", "z-"]],
  ["~", ["~", "z-"]],
  ["・", ["/", "z/"]],
  ["\u201c", ['"']],
  ["\u201d", ['"']],
  ["\u2019", ["'"]],
  ["￥", ["\\"]],
  ["「", ["["]],
  ["」", ["]"]],
])

// prettier-ignore
const ZENKAKU_LIST = ["０", "１", "２", "３", "４", "５", "６", "７", "８", "９", "Ａ", "Ｂ", "Ｃ", "Ｄ", "Ｅ", "Ｆ", "Ｇ", "Ｈ", "Ｉ", "Ｊ", "Ｋ", "Ｌ", "Ｍ", "Ｎ", "Ｏ", "Ｐ", "Ｑ", "Ｒ", "Ｓ", "Ｔ", "Ｕ", "Ｖ", "Ｗ", "Ｘ", "Ｙ", "Ｚ", "ａ", "ｂ", "ｃ", "ｄ", "ｅ", "ｆ", "ｇ", "ｈ", "ｉ", "ｊ", "ｋ", "ｌ", "ｍ", "ｎ", "ｏ", "ｐ", "ｑ", "ｒ", "ｓ", "ｔ", "ｕ", "ｖ", "ｗ", "ｘ", "ｙ", "ｚ", "＆", "％", "！", "？", "＠", "＃", "＄", "（", "）", "｜", "｛", "｝", "｀", "＊", "＋", "：", "；", "＿", "＜", "＞", "＝", "＾"]

export const convertZenkakuToHankaku = (char: string): string => {
  if (ZENKAKU_LIST.includes(char)) {
    return String.fromCharCode(char.charCodeAt(0) - 0xfee0)
  }
  return char
}

// prettier-ignore
const NN_LIST = ["あ", "い", "う", "え", "お", "な", "に", "ぬ", "ね", "の", "や", "ゆ", "よ", "ん", "'", "'", "a", "i", "u", "e", "o", "y", "n", "A", "I", "U", "E", "O", "Y", "N"]

// prettier-ignore
const SOKUON_JOIN_LIST = ["ヰ", "ゐ", "ヱ", "ゑ", "ぁ", "ぃ", "ぅ", "ぇ", "ぉ", "ゃ", "ゅ", "ょ", "っ", "ゎ", "ヵ", "ヶ", "ヴ", "か", "き", "く", "け", "こ", "さ", "し", "す", "せ", "そ", "た", "ち", "つ", "て", "と", "は", "ひ","ふ", "へ", "ほ", "ま", "み", "む", "め", "も", "や", "ゆ", "よ", "ら", "り", "る", "れ", "ろ", "わ", "を", "が", "ぎ", "ぐ", "げ", "ご", "ざ", "じ", "ず", "ぜ", "ぞ", "だ", "ぢ", "づ", "で", "ど", "ば", "び", "ぶ", "べ", "ぼ", "ぱ", "ぴ", "ぷ", "ぺ", "ぽ"]

export { NN_LIST, SOKUON_JOIN_LIST }
